on: 
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
name: Regenerate dockerfiles
jobs:
  regenerate:
    name: regenerate
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@main
      - 
        name: Regenerate and commit if changed
        run: |
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git config user.name "github-actions[bot]"
            ./scripts/update.sh
            git push

